server:
    port: 10600

logging:
    level:
        #org.springframework: debug
        com.neusoft.mapper: debug

spring:
    application:
        name: orders-server
    datasource:
        username: root
        password: 908520
        url: jdbc:mysql://localhost:3306/elm?characterEncoding=utf-8&serverTimezone=UTC
        driver-class-name: com.mysql.cj.jdbc.Driver
    main:
        #允许存在多个Feign调用相同Service的接口
        allow-bean-definition-overriding: true    

mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.neusoft.po
    
#eureka配置
eureka:
    client:
        service-url: 
            #将自己注册给Eureka Server集群
            defaultZone: http://eurekaServer13000:13000/eureka,http://eurekaServer13001:13001/eureka      
    instance:
        prefer-ip-address: true        #使用ip地址向Eureka注册
        instance-id: ${spring.cloud.client.ip-address}:${server.port} #自定义微服务实例ID
        lease-renewal-interval-in-seconds: 5         #续约间隔时间
        lease-expiration-duration-in-seconds: 15     #续约到期时间